### ISSUE TITLE
TypeError: Object #<Object> has no method 'debuglog'.

### ISSUE THREAD

**Issue by haani104** [Microsoft/TypeScript-Handbook#361]
I am getting below error upon doing gulp in my project. I am following https://www.typescriptlang.org/docs/handbook/gulp.html.

```
TypeError: Object #<Object> has no method 'debuglog'.

    at Object.<anonymous> (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/tsify/index.js:4:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/gulpfile.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

tsify version is 1.0.3
Node version is v0.10.30

Below is my Gulp File
```

var gulp = require("gulp");
var browserify = require("browserify");
var source = require('vinyl-source-stream');
var tsify = require("tsify");
var paths = {
    pages: ['src/*.html']
};

gulp.task("copy-html", function () {
    return gulp.src(paths.pages)
        .pipe(gulp.dest("dist"));
});

gulp.task("default", ["copy-html"], function () {
    return browserify({
        basedir: '.',
        debug: true,
        entries: ['src/main.ts'],
        cache: {},
        packageCache: {}
    })
    .plugin(tsify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest("dist"));
});
```

In node version 5.0.0 I get below error

```
[08:26:29] Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at tsify (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/tsify/index.js:9:30)
    at Browserify.plugin (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/browserify/index.js:353:9)
    at Gulp.<anonymous> (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/gulpfile.js:22:6)
    at module.exports (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/haani/learnspace/typescript/tutorials/Gulp/proj/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```
Typescript is globally installed as typescript@1.8.10

**Comment by DanielRosenwasser** [comment]
Sorry for the delay - I think the issue is you'll need a version of Node of 0.12 or above.
