### ISSUE TITLE
React & Webpack tutorial doesn't work

### ISSUE THREAD

**Issue by mbertram** [microsoft/TypeScript-Handbook#795]
The React & Webpack tutorial doesn't work. This is caused by changes to the current webpack version.

A warning is displayed when running the last step of the tutorial.

```
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "npm" to install the CLI via "npm install -D".
Which one do you like to install (webpack-cli/webpack-command):
```

Answering the question will install a local node module. This clashes with the global webpack module.

```
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at runCommand.then (/home/matt/.nvm/versions/node/v8.11.3/lib/node_modules/webpack/bin/webpack.js:152:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

PR #765 fixes this behaviour.

**Comment by mhegazy** [comment]
@DanielRosenwasser can you take a look
